CREATE TABLE STATUT(
    CATEGORIE CHAR(60) PRIMARY KEY
);
INSERT INTO STATUT(CATEGORIE) VALUES ('halal'), ('casher'), ('vegan'), ('vegetarien');
CREATE TABLE ARTICLE(
    TYPEA CHAR(60) PRIMARY KEY
);
INSERT INTO ARTICLE(TYPEA) VALUES ('boisson'), ('snack'), ('nouille'), ('autre');
CREATE TABLE SNACK(
    NOM_SNACK CHAR(60) PRIMARY KEY,
    PRIX FLOAT NOT NULL,
    BENEFICE FLOAT NOT NULL,
    DESCRIPTION VARCHAR,
    QUANTITE int NOT NULL,
    EN_VENTE int NOT NULL DEFAULT 1,
    A_ACHETER int NOT NULL,
    TYPEA CHAR(60) NOT NULL
);
ALTER TABLE SNACK ADD FOREIGN KEY (TYPEA) REFERENCES ARTICLE(TYPEA) ON DELETE CASCADE;
ALTER TABLE SNACK ADD CHEMIN_VERS_LIMAGE VARCHAR NOT NULL;
CREATE TABLE PERSONNE(
    NOM VARCHAR,
    PRENOM VARCHAR,
    ACTIF int NOT NULL DEFAULT 1,
    PRIMARY KEY (NOM, PRENOM)
);

CREATE TABLE PEUT_CONTENIR(
    CATEGORIE CHAR(60),
    NOM_SNACK CHAR(60),
    PRIMARY KEY (CATEGORIE, NOM_SNACK),
    FOREIGN KEY (CATEGORIE) REFERENCES STATUT(CATEGORIE) ON DELETE CASCADE,
    FOREIGN KEY (NOM_SNACK) REFERENCES SNACK(NOM_SNACK) ON DELETE CASCADE
);
CREATE TABLE HISTORIQUE_VENTE(
    DATE_ET_HEURE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP PRIMARY KEY
);

CREATE TABLE CONTENU_VENTE(
    NOM_SNACK CHAR(60),
    DATE_ET_HEURE TIMESTAMP WITHOUT TIME ZONE,
    OCCURRENCE INT,
    PRIMARY KEY (NOM_SNACK, DATE_ET_HEURE),
    FOREIGN KEY (NOM_SNACK) REFERENCES SNACK(NOM_SNACK) ON DELETE CASCADE,
    FOREIGN KEY (DATE_ET_HEURE) REFERENCES HISTORIQUE_VENTE(DATE_ET_HEURE) ON DELETE CASCADE
);

CREATE TABLE VENDU_PAR(
    DATE_ET_HEURE TIMESTAMP WITHOUT TIME ZONE,
    NOM VARCHAR,
    PRENOM VARCHAR,
    PRIMARY KEY (DATE_ET_HEURE, NOM, PRENOM),
    FOREIGN KEY (DATE_ET_HEURE) REFERENCES HISTORIQUE_VENTE(DATE_ET_HEURE) ON DELETE CASCADE,
    FOREIGN KEY (NOM, PRENOM) REFERENCES PERSONNE(NOM, PRENOM) ON DELETE CASCADE
);
