CREATE TABLE STATUT(
    CATEGORIE CHAR(60) PRIMARY KEY
);
INSERT INTO STATUT(CATEGORIE) VALUES ('halal'), ('casher'), ('vegan'), ('vegetarien');
CREATE TABLE ARTICLE(
    TYPEA CHAR(60) PRIMARY KEY
);
INSERT INTO ARTICLE(TYPEA) VALUES ('boisson'), ('snack'), ('nouille'), ('autre');
ALTER TABLE SNACK

CREATE TABLE SNACK(
    NOM_SNACK CHAR(60) PRIMARY KEY,
    PRIX FLOAT NOT NULL,
    PRIX_ACHAT FLOAT NOT NULL,
    DESCRIPTION VARCHAR,
    QUANTITE INT NOT NULL,
    EN_VENTE INT NOT NULL DEFAULT 1,
    RUPTURE INT NOT NULL,
    TYPEA CHAR(60) NOT NULL
    CHEMIN_VERS_LIMAGE VARCHAR NOT NULL;
);
ALTER TABLE SNACK ADD FOREIGN KEY (TYPEA) REFERENCES ARTICLE(TYPEA);
CREATE TABLE PERSONNE(
    NOM VARCHAR,
    PRENOM VARCHAR,
    ACTIF INT NOT NULL DEFAULT 1,
    PRIMARY KEY (NOM, PRENOM)
);
ALTER TABLE PEUT_CONTENIR ADD FOREIGN KEY (CATEGORIE) REFERENCES STATUT(CATEGORIE);
ALTER TABLE PEUT_CONTENIR ADD FOREIGN KEY (NOM_SNACK) REFERENCES SNACK(NOM_SNACK);

CREATE TABLE PEUT_CONTENIR(
    CATEGORIE CHAR(60),
    NOM_SNACK CHAR(60),
    PRIMARY KEY (CATEGORIE, NOM_SNACK),
    FOREIGN KEY (CATEGORIE) REFERENCES STATUT(CATEGORIE),
    FOREIGN KEY (NOM_SNACK) REFERENCES SNACK(SNACK)
);
CREATE TABLE HISTORIQUE_VENTE(
    DATE_ET_HEURE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP PRIMARY KEY
);
ALTER TABLE CONTENU_VENTE ADD FOREIGN KEY (NOM_SNACK) REFERENCES SNACK(NOM_SNACK);
ALTER TABLE CONTENU_VENTE ADD FOREIGN KEY (DATE_ET_HEURE) REFERENCES HISTORIQUE_VENTE(DATE_ET_HEURE);
CREATE TABLE CONTENU_VENTE(
    NOM_SNACK CHAR(60),
    DATE_ET_HEURE TIMESTAMP WITHOUT TIME ZONE,
    OCCURRENCE INT,
    PRIMARY KEY (NOM_SNACK, DATE_ET_HEURE),
    FOREIGN KEY (NOM_SNACK) REFERENCES SNACK(NOM_SNACK),
    FOREIGN KEY (DATE_ET_HEURE) REFERENCES HISTORIQUE_VENTE(DATE_ET_HEURE)
);
ALTER TABLE VENDU_PAR ADD FOREIGN KEY (DATE_ET_HEURE) REFERENCES HISTORIQUE_VENTE(DATE_ET_HEURE);
ALTER TABLE VENDU_PAR ADD FOREIGN KEY (NOM, PRENOM) REFERENCES PERSONNE(NOM, PRENOM);
CREATE TABLE VENDU_PAR(
    DATE_ET_HEURE TIMESTAMP WITHOUT TIME ZONE,
    NOM VARCHAR,
    PRENOM VARCHAR,
    PRIMARY KEY (DATE_ET_HEURE, NOM, PRENOM),
    FOREIGN KEY (DATE_ET_HEURE) REFERENCES HISTORIQUE_VENTE(DATE_ET_HEURE),
    FOREIGN KEY (NOM, PRENOM) REFERENCES PERSONNE(NOM, PRENOM)
);
